id: healthcare-application-review
name: Healthcare Application Review
description: Design review template for applications in the healthcare industry focusing on MongoDB database design and performance optimization.
version: "1.0"
type: design-review
metadata:
  author: Design Assistant
  lastUpdated: "2024-11-15"
  tags:
    - healthcare
    - compliance
    - performance
    - design-review

globalPromptContext: |
  As a MongoDB Solutions Architect, analyze this healthcare application design with a focus on:
  - Handling sensitive patient data (e.g., PHI)
  - Compliance with regulations like HIPAA, GDPR, or SOC 2
  - Schema design and indexing strategies
  - Performance optimization for healthcare-specific use cases
  - High availability and disaster recovery for critical systems
  - Security and access control tailored to healthcare environments

  Consider MongoDB's latest features (7.0+) and provide specific, actionable recommendations.

sections:
  - id: customer-details
    title: Customer Information
    description: Basic information about the healthcare organization and project
    questions:
      - id: customer-name
        type: text
        label: Customer Name
        required: true
        placeholder: Legal name of the healthcare organization
        promptContext: |
          Use this information to contextualize recommendations based on the organization's size and industry positioning.

      - id: project-name
        type: text
        label: Project Name
        required: true
        placeholder: Internal name for the healthcare application
        promptContext: |
          Assess project naming conventions for relevance in database naming and documentation.

      - id: industry-specific-details
        type: textarea
        label: Industry-Specific Details
        required: true
        placeholder: Provide any unique details or challenges related to healthcare
        promptContext: |
          Use this information to identify specific data handling and compliance needs in the healthcare domain.

  - id: patient-data-management
    title: Patient Data Management
    description: Details about handling patient information and medical records
    questions:
      - id: data-types
        type: select
        label: Types of Patient Data Stored
        required: true
        options:
          - Demographics (Name, Age, Address)
          - Medical Records (Diagnosis, Treatments, Test Results)
          - Billing Information
          - Imaging Data (X-rays, MRIs, CT Scans)
          - Other
        promptContext: |
          For each data type, assess the schema design, indexing requirements, and storage optimization strategies.

      - id: pii-handling
        type: checkbox-group
        label: Personally Identifiable Information (PII) Handling
        required: true
        options:
          - Encryption at Rest
          - Field-Level Encryption
          - Masking/Scrubbing in Non-Prod
          - Access Control Restrictions
          - Audit Logging
        promptContext: |
          Analyze the PII handling strategy for compliance with HIPAA or equivalent regulations and its impact on performance.

      - id: access-patterns
        type: dynamic-list
        label: Access Patterns for Patient Data
        required: true
        fields:
          - name: pattern_name
            label: Pattern Name
            type: text
          - name: description
            label: Description
            type: textarea
          - name: frequency
            label: Frequency
            type: select
            options:
              - High
              - Medium
              - Low
        promptContext: |
          Evaluate access patterns to optimize the schema design, recommend indexing strategies, and suggest caching where applicable.

  - id: compliance-requirements
    title: Compliance and Security Requirements
    description: Legal and regulatory compliance and associated database configurations
    questions:
      - id: compliance-standards
        type: checkbox-group
        label: Compliance Standards
        required: true
        options:
          - HIPAA
          - GDPR
          - SOC 2
          - ISO 27001
          - Other
        promptContext: |
          Evaluate the database design and operations for compliance with selected standards, and recommend configurations or features like encryption and access control.

      - id: security-requirements
        type: checkbox-group
        label: Security Features
        required: true
        options:
          - Role-Based Access Control
          - SSL/TLS Encryption
          - IP Access Lists
          - Field-Level Encryption
          - Audit Logging
          - Network Isolation
        promptContext: |
          Analyze the security configurations and recommend best practices for ensuring patient data protection.

  - id: performance-requirements
    title: Performance and Scalability
    description: Performance considerations for high-demand healthcare use cases
    questions:
      - id: transaction-volumes
        type: select
        label: Peak Transaction Volumes
        required: true
        options:
          - "< 1,000 ops/sec"
          - "1,000 - 10,000 ops/sec"
          - "10,000 - 100,000 ops/sec"
          - "> 100,000 ops/sec"
        promptContext: |
          Evaluate peak transaction volumes and recommend scaling strategies, cluster configurations, and sharding if applicable.

      - id: response-time-requirements
        type: number
        label: Response Time Requirements (ms)
        required: true
        promptContext: |
          Analyze latency requirements and recommend optimization strategies, including index tuning and query optimizations.

  - id: operational-requirements
    title: Operational Considerations
    description: Database operations and maintenance specifics for healthcare applications
    questions:
      - id: backup-strategies
        type: checkbox-group
        label: Backup and Recovery Strategies
        required: true
        options:
          - Point-in-Time Recovery
          - Cross-Region Backups
          - Continuous Backups
          - Custom Backup Schedules
        promptContext: |
          Recommend robust backup and recovery strategies tailored for critical healthcare applications.

      - id: maintenance-windows
        type: textarea
        label: Maintenance Windows
        placeholder: Specify preferred maintenance windows and constraints
        promptContext: |
          Suggest best practices for maintenance, ensuring minimal downtime for critical operations.

analysisPromptTemplate: |
  Based on the provided information, generate a comprehensive analysis document with the following sections:

  # MongoDB Healthcare Application Design Review
  
  ## Executive Summary
  - Overview of the application and its purpose
  - Key challenges and requirements
  - Critical recommendations
  
  ## Technical Analysis
  - Data model evaluation
  - Performance considerations
  - Security and compliance assessment
  
  ## Architecture Recommendations
  - Schema design and indexing
  - Access pattern optimizations
  - Deployment and scaling strategies
  
  ## Implementation Guidance
  - Security configuration best practices
  - Backup and recovery strategies
  - Maintenance and operational excellence
  
  ## Risk Assessment
  - Compliance risks
  - Operational risks
  - Mitigation strategies
  
  ## Next Steps
  - Immediate actions
  - Short-term improvements
  - Long-term recommendations
  
  ## References
  - Relevant MongoDB documentation and best practices
  - Industry-specific compliance guidelines
