id: new-application-comprehensive
name: Comprehensive New Application Review
description: Comprehensive design review template for new applications being built on MongoDB
version: "1.0"
type: design-review
metadata:
  author: Michael Lynn
  lastUpdated: "2024-11-15"
  tags: 
    - new-development
    - architecture
    - infrastructure
    - design-review

globalPromptContext: |
  As a MongoDB Solutions Architect, analyze this new application design with focus on:
  - Data model optimization and schema design
  - Access patterns and query optimization
  - Scaling and performance considerations
  - High availability and disaster recovery
  - Security and compliance requirements
  - Operational excellence
  
  Consider MongoDB's latest features (7.0+) and provide specific, actionable recommendations.

sections:
  - id: customer-details
    title: Customer Information
    description: Basic customer and project information
    questions:
      - id: customer-name
        type: text
        label: Customer Name
        required: true
        placeholder: Legal name of the customer organization
        promptContext: |
          Use this information to contextualize recommendations and identify relevant industry patterns.

      - id: project-name
        type: text
        label: Project Name
        required: true
        placeholder: Internal name for the project
        promptContext: |
          Consider project naming conventions and potential database naming implications.

      - id: customer-contacts
        type: dynamic-list
        label: Key Contacts
        required: true
        fields:
          - name: name
            label: Contact Name
            type: text
          - name: role
            label: Role
            type: text
          - name: email
            label: Email
            type: email
        promptContext: |
          Maintain contact information for project stakeholders.

      - id: industry
        type: select
        label: Industry
        required: true
        options:
          - Financial Services
          - Healthcare
          - Retail/eCommerce
          - Technology
          - Manufacturing
          - Government
          - Education
          - Other
        promptContext: |
          Consider industry-specific:
          - Compliance requirements
          - Data protection needs
          - Common usage patterns
          - Performance expectations

  - id: project-overview
    title: Project Overview
    description: High-level project information and timelines
    questions:
      - id: project-description
        type: textarea
        label: Project Description
        required: true
        placeholder: Detailed description of the project goals and scope
        promptContext: |
          Analyze the project scope to identify:
          - Key MongoDB features needed
          - Potential architectural challenges
          - Scaling considerations
          - Integration requirements

      - id: target-release
        type: date
        label: Target Release Date
        required: true
        promptContext: |
          Consider timeline implications for:
          - Development phases
          - Data migration needs
          - Performance testing
          - Production readiness

      - id: project-phases
        type: dynamic-list
        label: Project Phases
        fields:
          - name: phase_name
            label: Phase Name
            type: text
          - name: description
            label: Description
            type: textarea
          - name: timeline
            label: Timeline
            type: text
        promptContext: |
          Evaluate phase-specific requirements and provide recommendations for each stage.

  - id: technical-requirements
    title: Technical Requirements
    description: Detailed technical requirements and constraints
    questions:
      - id: deployment-type
        type: select
        label: Deployment Type
        required: true
        options:
          - Atlas Serverless
          - Atlas Dedicated
          - Atlas Charts
          - On-Premises
          - Self-Managed Cloud
        promptContext: |
          Based on deployment type, analyze:
          1. Infrastructure requirements
          2. Operational considerations
          3. Monitoring and management needs
          4. Cost implications
          5. Scaling capabilities

      - id: scale-requirements
        type: multi-select
        label: Scale Requirements
        required: true
        options:
          - name: data-size
            label: Expected Data Size
            options:
              - "< 100GB"
              - "100GB - 1TB"
              - "1TB - 10TB"
              - "> 10TB"
          - name: operations
            label: Peak Operations/Second
            options:
              - < 1,000 ops/sec
              - "1,000 - 10,000 ops/sec"
              - "10,000 - 100,000 ops/sec"
              - "> 100,000 ops/sec"
          - name: concurrent-users
            label: Concurrent Users
            options:
              - "< 100 users"
              - "100 - 1,000 users"
              - "1,000 - 10,000 users"
              - "> 10,000 users"
        promptContext: |
          Analyze scale requirements to recommend:
          1. Cluster sizing and configuration
          2. Sharding strategy if needed
          3. Index design considerations
          4. Connection pooling settings
          5. Resource allocation

      - id: availability-requirements
        type: checkbox-group
        label: Availability Requirements
        required: true
        options:
          - High Availability Required
          - Disaster Recovery Required
          - Multi-Region Distribution
          - Active-Active Configuration
          - Zero-Downtime Maintenance
          - Automatic Failover
        promptContext: |
          Based on availability requirements, recommend:
          1. Cluster topology
          2. Replication configuration
          3. Backup strategies
          4. Disaster recovery procedures
          5. Maintenance strategies

      - id: performance-requirements
        type: dynamic-list
        label: Performance Requirements
        fields:
          - name: operation_type
            label: Operation Type
            type: select
            options:
              - Read
              - Write
              - Update
              - Delete
              - Aggregate
          - name: latency_requirement
            label: Latency Requirement (ms)
            type: number
          - name: throughput_requirement
            label: Throughput Requirement (ops/sec)
            type: number
        promptContext: |
          For each operation type:
          1. Evaluate feasibility
          2. Recommend optimization strategies
          3. Suggest index designs
          4. Consider read/write concerns
          5. Propose caching strategies

  - id: data-architecture
    title: Data Architecture
    description: Data model and access patterns
    questions:
      - id: data-model
        type: file-upload
        label: Data Model Documentation
        accept: .json,.yaml,.md
        multiple: true
        required: true
        promptContext: |
          Review data models for:
          1. Schema design best practices
          2. Indexing opportunities
          3. Potential anti-patterns
          4. Optimization possibilities
          5. Consistency requirements

      - id: access-patterns
        type: dynamic-list
        label: Access Patterns
        required: true
        fields:
          - name: pattern_name
            label: Pattern Name
            type: text
          - name: description
            label: Description
            type: textarea
          - name: frequency
            label: Frequency
            type: select
            options:
              - High
              - Medium
              - Low
          - name: consistency_requirements
            label: Consistency Requirements
            type: select
            options:
              - Strong
              - Eventually Consistent
        promptContext: |
          For each access pattern:
          1. Evaluate data model implications
          2. Suggest indexing strategies
          3. Consider read/write concerns
          4. Recommend optimization approaches
          5. Assess scaling impact

  - id: security-compliance
    title: Security and Compliance
    description: Security requirements and compliance needs
    questions:
      - id: security-requirements
        type: checkbox-group
        label: Security Requirements
        required: true
        options:
          - Network Isolation
          - Field-Level Encryption
          - Client-Side Field-Level Encryption
          - Authentication Required
          - Role-Based Access Control
          - Audit Logging
          - SSL/TLS Encryption
          - IP Access Lists
        promptContext: |
          Based on security requirements:
          1. Recommend security features
          2. Suggest configuration settings
          3. Outline best practices
          4. Address potential vulnerabilities
          5. Consider performance impact

      - id: compliance-requirements
        type: checkbox-group
        label: Compliance Requirements
        options:
          - SOC 2
          - HIPAA
          - PCI-DSS
          - GDPR
          - FedRAMP
          - ISO 27001
          - Other
        promptContext: |
          For each compliance requirement:
          1. Identify necessary controls
          2. Suggest configuration settings
          3. Recommend monitoring approaches
          4. Consider data residency needs
          5. Address audit requirements

  - id: operational-requirements
    title: Operational Requirements
    description: Operational needs and constraints
    questions:
      - id: monitoring-requirements
        type: checkbox-group
        label: Monitoring Requirements
        required: true
        options:
          - Performance Monitoring
          - Alerting
          - Custom Metrics
          - Log Analysis
          - Query Performance Analysis
          - Capacity Planning
        promptContext: |
          Design monitoring strategy considering:
          1. Key metrics to track
          2. Alert thresholds
          3. Response procedures
          4. Performance baselines
          5. Capacity planning

      - id: backup-requirements
        type: checkbox-group
        label: Backup Requirements
        required: true
        options:
          - Point-in-Time Recovery
          - Continuous Backup
          - Cross-Region Backup
          - Custom Backup Schedule
          - Long-Term Retention
        promptContext: |
          Design backup strategy addressing:
          1. Recovery point objectives
          2. Recovery time objectives
          3. Retention policies
          4. Testing procedures
          5. Restoration processes

      - id: maintenance-windows
        type: textarea
        label: Maintenance Requirements
        placeholder: Describe maintenance windows and constraints
        promptContext: |
          Plan maintenance procedures for:
          1. Version upgrades
          2. Index builds
          3. Configuration changes
          4. Performance tuning
          5. Security updates

analysisPromptTemplate: |
  Based on the provided information, generate a comprehensive analysis document with the following sections:

  # MongoDB Application Design Review
  
  ## Executive Summary
  - Project overview
  - Key requirements
  - Critical recommendations
  
  ## Technical Analysis
  - Infrastructure recommendations
  - Data model evaluation
  - Performance considerations
  - Security assessment
  
  ## Architecture Recommendations
  - Deployment architecture
  - Scaling strategy
  - High availability design
  - Security implementation
  
  ## Implementation Guidance
  - Development best practices
  - Testing recommendations
  - Migration approach
  - Operational procedures
  
  ## Risk Assessment
  - Technical risks
  - Operational risks
  - Mitigation strategies
  
  ## Next Steps
  - Immediate actions
  - Short-term recommendations
  - Long-term considerations
  
  ## References
  - Relevant documentation
  - Best practices guides
  - Example implementations